#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Use priority 40 that's below lightdm-gtk-greeter's 60 while in experimental
    update-alternatives --install /usr/share/xgreeters/lightdm-greeter.desktop \
    lightdm-greeter /usr/share/xgreeters/io.elementary.greeter.desktop 40
fi

#DEBHELPER#
