#!/bin/sh
set -e

case "$1" in
  remove|purge)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
        /usr/lib/lightdm/lightdm-set-defaults --remove --greeter=pantheon-greeter || true
    fi
  ;;
esac

#DEBHELPER#

